//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDR_MENU1                       101
#define IDR_CHM                         102
#define IDD_SETTINGS                    103
#define IDI_APPICON                     104
#define IDC_SETTINGS_GRAPHICS_API       1001
#define IDC_SETTINGS_CAPTURE_API        1002
#define IDC_SETTINGS_STATUS             1003
#define IDC_SETTINGS_MOUSE_RELATIVE_ZOOM 1004
#define IDC_SETTINGS_UI_API             1005
#define IDC_SETTINGS_TEXT_RENDERER      1006
#define IDC_SETTINGS_PRESENT_TARGET     1007
#define IDC_SETTINGS_SURFACE_OWNERSHIP  1008
#define IDC_SETTINGS_COMPOSITION_HOST   1009
#define IDC_SETTINGS_COPY_REQUIREMENT   1010
#define IDC_SETTINGS_ALPHA_MODE         1011
#define IDC_SETTINGS_DISPLAY_ADAPTER    1012
#define IDC_SETTINGS_HARDWARE_ADAPTER   1013
#define IDC_SETTINGS_STRICT_TARGET      1014
#define IDC_SETTINGS_ALLOW_TEARING      1015
#define IDC_SETTINGS_BUFFER_COUNT       1016
#define IDC_SETTINGS_FRAME_LATENCY      1017
#define IDC_SETTINGS_SYNC_INTERVAL      1018
#define IDC_SETTINGS_CONSTANT_ALPHA     1019
#define IDC_SETTINGS_COLOR_KEY          1020
#define ID_CONTEXTMENU_FOCUS            40005
#define ID_CONTEXTMENU_HELP             40006
#define ID_CONTEXTMENU_CLOSE            40007
#define ID_CONTEXTMENU_FOLLOW_MOUSE     40008
#define ID_CONTEXTMENU_SETTINGS         40009
#define ID_CONTEXTMENU_WINDOW_MODE      40010
#define ID_CONTEXTMENU_LENS_MODE        40011
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40012
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
