//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDR_MENU1                       101
#define IDR_CHM                         102
#define IDD_SETTINGS                    103
#define IDI_APPICON                     104
#define IDC_SETTINGS_GRAPHICS_API       1001
#define IDC_SETTINGS_CAPTURE_API        1002
#define IDC_SETTINGS_STATUS             1003
#define IDC_SETTINGS_MOUSE_RELATIVE_ZOOM 1004
#define IDC_SETTINGS_UI_API             1005
#define IDC_SETTINGS_TEXT_RENDERER      1006
#define IDC_SETTINGS_PRESENT_TARGET     1007
#define IDC_SETTINGS_SURFACE_OWNERSHIP  1008
#define IDC_SETTINGS_COMPOSITION_HOST   1009
#define IDC_SETTINGS_COPY_REQUIREMENT   1010
#define IDC_SETTINGS_ALPHA_MODE         1011
#define IDC_SETTINGS_DISPLAY_ADAPTER    1012
#define IDC_SETTINGS_HARDWARE_ADAPTER   1013
#define IDC_SETTINGS_STRICT_TARGET      1014
#define IDC_SETTINGS_ALLOW_TEARING      1015
#define IDC_SETTINGS_BUFFER_COUNT       1016
#define IDC_SETTINGS_FRAME_LATENCY      1017
#define IDC_SETTINGS_SYNC_INTERVAL      1018
#define IDC_SETTINGS_CONSTANT_ALPHA     1019
#define IDC_SETTINGS_COLOR_KEY          1020
#define IDC_SETTINGS_TAB                1021
#define IDC_SETTINGS_LABEL_GRAPHICS_API 1022
#define IDC_SETTINGS_LABEL_CAPTURE_API  1023
#define IDC_SETTINGS_LABEL_UI_API       1024
#define IDC_SETTINGS_LABEL_TEXT_RENDERER 1025
#define IDC_SETTINGS_LABEL_PRESENT_TARGET 1026
#define IDC_SETTINGS_LABEL_SURFACE_OWNERSHIP 1027
#define IDC_SETTINGS_LABEL_COMPOSITION_HOST 1028
#define IDC_SETTINGS_LABEL_COPY_REQUIREMENT 1029
#define IDC_SETTINGS_LABEL_ALPHA_MODE   1030
#define IDC_SETTINGS_LABEL_DISPLAY_ADAPTER 1031
#define IDC_SETTINGS_LABEL_HARDWARE_ADAPTER 1032
#define IDC_SETTINGS_LABEL_CONSTANT_ALPHA 1033
#define IDC_SETTINGS_LABEL_COLOR_KEY    1034
#define IDC_SETTINGS_LABEL_ALPHA_NOTE   1035
#define IDC_SETTINGS_LABEL_BUFFER_COUNT 1036
#define IDC_SETTINGS_LABEL_FRAME_LATENCY 1037
#define IDC_SETTINGS_LABEL_SYNC_INTERVAL 1038
#define IDC_SETTINGS_VALUE_CONSTANT_ALPHA 1039
#define IDC_SETTINGS_VALUE_BUFFER_COUNT  1040
#define IDC_SETTINGS_VALUE_FRAME_LATENCY 1041
#define IDC_SETTINGS_VALUE_SYNC_INTERVAL 1042
#define IDC_SETTINGS_PRESET             1043
#define IDC_SETTINGS_LABEL_PRESET       1044
#define IDC_SETTINGS_ROUTE_DIAGRAM      1045
#define IDC_SETTINGS_ROUTE_PACING       1046
#define IDC_SETTINGS_ROUTE_LAYERING     1047
#define IDC_SETTINGS_LABEL_STRICT_TARGET 1048
#define IDC_SETTINGS_LABEL_ALLOW_TEARING 1049
#define IDC_SETTINGS_LABEL_MOUSE_RELATIVE_ZOOM 1050
#define IDC_SETTINGS_WAITABLE_SWAP_CHAIN 1051
#define IDC_SETTINGS_LABEL_WAITABLE_SWAP_CHAIN 1052
#define ID_CONTEXTMENU_FOCUS            40005
#define ID_CONTEXTMENU_HELP             40006
#define ID_CONTEXTMENU_CLOSE            40007
#define ID_CONTEXTMENU_FOLLOW_MOUSE     40008
#define ID_CONTEXTMENU_SETTINGS         40009
#define ID_CONTEXTMENU_WINDOW_MODE      40010
#define ID_CONTEXTMENU_LENS_MODE        40011
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40012
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
